export const INSTRUCTOR_LIST_REQUEST = 'INSTRUCTOR_LIST_REQUEST';
export const INSTRUCTOR_LIST_SUCCESS = 'INSTRUCTOR_LIST_SUCCESS';
export const INSTRUCTOR_LIST_FAIL  = 'INSTRUCTOR_LIST_FAIL ';

export const LEARNER_LIST_REQUEST = 'LEARNER_LIST_REQUEST';
export const LEARNER_LIST_SUCCESS = 'LEARNER_LIST_SUCCESS';
export const LEARNER_LIST_FAIL  = 'LEARNER_LIST_FAIL ';

export const UPDATE_USER_BY_ID_REQUEST = 'UPDATE_USER_BY_ID_REQUEST';
export const UPDATE_USER_BY_ID_SUCCESS = 'UPDATE_USER_BY_ID_SUCCESS';
export const UPDATE_USER_BY_ID_FAIL  = 'UPDATE_USER_BY_ID_FAIL ';

export const DELETE_USER_BY_ID_REQUEST = 'DELETE_USER_BY_ID_REQUEST';
export const DELETE_USER_BY_ID_SUCCESS = 'DELETE_USER_BY_ID_SUCCESS';
export const DELETE_USER_BY_ID_FAIL  = 'DELETE_USER_BY_ID_FAIL ';
