export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE  = 'LOGIN_FAILURE ';
export const USER_LOGOUT  = 'USER_LOGOUT ';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE  = 'REGISTER_FAILURE ';

export const USER_VIEW_REQUEST  = 'USER_VIEW_REQUEST ';
export const USER_VIEW_SUCCESS = 'USER_VIEW_SUCCESS';
export const USER_VIEW_FAIL  = 'USER_VIEW_FAIL ';

export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAIL  = 'UPDATE_FAIL ';