apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway-service
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service
        ports:
        - containerPort: 5002
        env:
        - name: MONGO_URI
          value: "mongodb+srv://Academify:academifySLIIT@academify.bglxvis.mongodb.net"
        - name: TOKEN_SECRET
          value: "academify2024"
        - name: ADMIN_EMAIL
          value: "academify@admin.com"
        - name: ADMIN_PASSWORD
          value: "academifySLIIT"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: course-service
        ports:
        - containerPort: 5005
        env:
        - name: MONGO_URI
          value: "mongodb+srv://Academify:academifySLIIT@academify.bglxvis.mongodb.net"
        - name: TOKEN_SECRET
          value: "academify2024"
        - name: ADMIN_EMAIL
          value: "academify@admin.com"
        - name: ADMIN_PASSWORD
          value: "academifySLIIT"
---
apiVersion: v1
kind: Service
metadata:
  name: course-service-service
spec:
  selector:
    app: course-service
  ports:
  - protocol: TCP
    port: 5005
    targetPort: 5005
