export const ENROLL_COURSE_REQUEST = 'ENROLL_COURSE_REQUEST';
export const ENROLL_COURSE_SUCCESS = 'ENROLL_COURSE_SUCCESS';
export const ENROLL_COURSE_FAIL = 'ENROLL_COURSE_FAIL';

export const ENROLL_GET_ALL_REQUEST = "ENROLL_GET_ALL_REQUEST";
export const ENROLL_GET_ALL_SUCCESS = "ENROLL_GET_ALL_SUCCESS";
export const ENROLL_GET_ALL_FAIL = "ENROLL_GET_ALL_FAIL";

export const ENROLL_GET_REQUEST = "ENROLL_GET_REQUEST";
export const ENROLL_GET_SUCCESS = "ENROLL_GET_SUCCESS";
export const ENROLL_GET_FAIL = "ENROLL_GET_FAIL";

export const ENROLL_UPDATE_REQUEST = "ENROLL_UPDATE_REQUEST";
export const ENROLL_UPDATE_SUCCESS = "ENROLL_UPDATE_SUCCESS";
export const ENROLL_UPDATE_FAIL = "ENROLL_UPDATE_FAIL";

export const ENROLL_DELETE_REQUEST = 'ENROLL_DELETE_REQUEST';
export const ENROLL_DELETE_SUCCESS = 'ENROLL_DELETE_SUCCESS';
export const ENROLL_DELETE_FAIL = 'ENROLL_DELETE_FAIL';

export const ENROLLS_GET_BY_ID_REQUEST = "ENROLLS_GET_BY_ID_REQUEST";
export const ENROLLS_GET_BY_ID_SUCCESS = "ENROLLS_GET_BY_ID_SUCCESS";
export const ENROLLS_GET_BY_ID_FAIL = "ENROLLS_GET_BY_ID_FAIL";
