export const ADD_CONTENT_REQUEST = 'ADD_CONTENT_REQUEST';
export const ADD_CONTENT_SUCCESS = 'ADD_CONTENT_SUCCESS';
export const ADD_CONTENT_FAILURE = 'ADD_CONTENT_FAILURE';

export const GET_CONTENT_FOR_COURSE_REQUEST = 'GET_CONTENT_FOR_COURSE_REQUEST';
export const GET_CONTENT_FOR_COURSE_SUCCESS = 'GET_CONTENT_FOR_COURSE_SUCCESS';
export const GET_CONTENT_FOR_COURSE_FAILURE = 'GET_CONTENT_FOR_COURSE_FAILURE';

export const GET_SPECIFIC_CONTENT_REQUEST = 'GET_SPECIFIC_CONTENT_REQUEST';
export const GET_SPECIFIC_CONTENT_SUCCESS = 'GET_SPECIFIC_CONTENT_SUCCESS';
export const GET_SPECIFIC_CONTENT_FAILURE = 'GET_SPECIFIC_CONTENT_FAILURE';

export const UPDATE_CONTENT_REQUEST = 'UPDATE_CONTENT_REQUEST';
export const UPDATE_CONTENT_SUCCESS = 'UPDATE_CONTENT_SUCCESS';
export const UPDATE_CONTENT_FAILURE = 'UPDATE_CONTENT_FAILURE';