export const COURSE_CREATE_REQUEST = "COURSE_CREATE_REQUEST";
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS";
export const COURSE_CREATE_FAIL = "COURSE_CREATE_FAIL";

export const COURSE_GET_ALL_REQUEST = "COURSE_GET_ALL_REQUEST";
export const COURSE_GET_ALL_SUCCESS = "COURSE_GET_ALL_SUCCESS";
export const COURSE_GET_ALL_FAIL = "COURSE_GET_ALL_FAIL";

export const COURSE_GET_REQUEST = "COURSE_GET_REQUEST";
export const COURSE_GET_SUCCESS = "COURSE_GET_SUCCESS";
export const COURSE_GET_FAIL = "COURSE_GET_FAIL";

export const COURSE_UPDATE_REQUEST = "COURSE_UPDATE_REQUEST";
export const COURSE_UPDATE_SUCCESS = "COURSE_UPDATE_SUCCESS";
export const COURSE_UPDATE_FAIL = "COURSE_UPDATE_FAIL";

export const COURSE_DELETE_REQUEST = "COURSE_DELETE_REQUEST";
export const COURSE_DELETE_SUCCESS = "COURSE_DELETE_SUCCESS";
export const COURSE_DELETE_FAIL = "COURSE_DELETE_FAIL";

export const COURSES_GET_BY_ID_REQUEST = "COURSES_GET_BY_ID_REQUEST";
export const COURSES_GET_BY_ID_SUCCESS = "COURSES_GET_BY_ID_SUCCESS";
export const COURSES_GET_BY_ID_FAIL = "COURSES_GET_BY_ID_FAIL";